version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - BACKEND_RELOAD=true
      - BACKEND_LOG_LEVEL=info
    env_file:
      - env.example
    depends_on:
      - postgres
    networks:
      - setlist-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
      - /app/node_modules
    environment:
      - FRONTEND_PORT=3000
      - FRONTEND_HOST=0.0.0.0
    env_file:
      - env.example
    networks:
      - setlist-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: setlist_dev
      POSTGRES_USER: setlist_user
      POSTGRES_PASSWORD: setlist_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - setlist-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - setlist-network

volumes:
  postgres_data:

networks:
  setlist-network:
    driver: bridge
