version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - BACKEND_RELOAD=true
      - BACKEND_LOG_LEVEL=info
      - DATABASE_URL=${SUPABASE_DATABASE_URL}
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - setlist-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
      - /app/node_modules
    environment:
      - FRONTEND_PORT=3000
      - FRONTEND_HOST=0.0.0.0
    env_file:
      - .env
    networks:
      - setlist-network



  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - setlist-network

volumes: {}

networks:
  setlist-network:
    driver: bridge
