"""Update artist profiles to use JSON columns

Revision ID: 086d95ff9952
Revises: c9f14bfb1729
Create Date: 2025-08-29 20:00:38.730673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086d95ff9952'
down_revision = 'c9f14bfb1729'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert TEXT to JSON with proper casting
    op.execute("ALTER TABLE artist_profiles ALTER COLUMN genres TYPE JSON USING genres::json")
    op.execute("ALTER TABLE artist_profiles ALTER COLUMN instruments TYPE JSON USING instruments::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist_profiles', 'instruments',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('artist_profiles', 'genres',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
