"""Add collaborations table

Revision ID: db26c6fa02e1
Revises: 086d95ff9952
Create Date: 2025-08-29 20:26:39.163308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db26c6fa02e1'
down_revision = '086d95ff9952'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborations',
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('target_artist_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_artist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborations_id'), 'collaborations', ['id'], unique=False)
    op.alter_column('music_tracks', 'genre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # Fix JSON casting for tags column
    op.execute("ALTER TABLE music_tracks ALTER COLUMN tags TYPE JSON USING tags::json")
    op.alter_column('music_tracks', 'audio_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music_tracks', 'audio_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('music_tracks', 'tags',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('music_tracks', 'genre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_collaborations_id'), table_name='collaborations')
    op.drop_table('collaborations')
    # ### end Alembic commands ###
