"""add_profile_picture_binary_to_artist_profiles

Revision ID: ec38744a2971
Revises: db26c6fa02e1
Create Date: 2025-08-29 21:18:46.114737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec38744a2971'
down_revision = 'db26c6fa02e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_profiles', sa.Column('profile_picture_binary', sa.LargeBinary(), nullable=True))
    op.add_column('artist_profiles', sa.Column('profile_picture_content_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_profiles', 'profile_picture_content_type')
    op.drop_column('artist_profiles', 'profile_picture_binary')
    # ### end Alembic commands ###
